# Generated by Django 5.1.3 on 2024-11-29 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Restaura", "0003_restaurantes"),
    ]

    operations = [
        migrations.DeleteModel(
            name="userview",
        ),
    ]
