# Generated by Django 5.1.3 on 2024-12-02 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Restaura", "0004_delete_userview"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cart",
            unique_together={("user",)},
        ),
        migrations.AlterUniqueTogether(
            name="order",
            unique_together={("menu",)},
        ),
        migrations.AddField(
            model_name="cart",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("shipped", "Shipped"),
                    ("completed", "Completed"),
                ],
                default=1,
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="menu",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="Restaura.menuitems",
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="cart",
            name="category",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="menuitem",
        ),
        migrations.RemoveField(
            model_name="order",
            name="cart",
        ),
        migrations.RemoveField(
            model_name="order",
            name="status",
        ),
    ]
