# Generated by Django 5.1.3 on 2024-12-02 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Restaura", "0005_alter_cart_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cart",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="order",
            unique_together={("user", "menu")},
        ),
        migrations.AddField(
            model_name="cart",
            name="orden",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="Restaura.order",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="cart",
            unique_together={("user", "orden")},
        ),
    ]
